safe: false

relative_source: ../aydrian.github.io/
destination: ./_site/

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: aydrian
repo: aydrian.github.io
branch: develop

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
highlighter: pygments
markdown: kramdown
# disqus: dbyll
# google_analytics: dbyll
title: aydrian.me

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: aydrian.me

description: Stylish Jekyll Theme
author:
  name: Aydrian J Howard
  email: hello@aydrian.me
  github: aydrian
  twitter: haybien
  # pinterest: asd123
  # linkedin: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
