safe: false
lsi: false
pygments: true

relative_source: ../aydrian.github.io/
destination: ../aydrian.github.io/_site

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: aydrian
repo: aydrian.github.io
branch: master

# Site settings
title: aydrian.me
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aydrian.me" # the base hostname & protocol for your site
twitter_username: aydrianh
github_username:  aydrian

# Build settings
markdown: kramdown

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
